# Generated by Django 4.2 on 2024-06-02 21:51

from django.db import migrations, models
import django.db.models.deletion
import entrega.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('telefono', models.CharField(blank=True, max_length=10)),
                ('direccion', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            bases=(models.Model, entrega.models.ModeloBase),
        ),
        migrations.CreateModel(
            name='Nafta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_litro', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrega', to='entrega.cliente')),
                ('nafta', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='entrega.nafta')),
            ],
            bases=(models.Model, entrega.models.ModeloBase),
        ),
    ]
