# Generated by Django 4.2 on 2024-06-05 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('entrega', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entregasUsuario', to='usuario.usuario'),
        ),
    ]
