# Generated by Django 4.2 on 2024-09-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrega', '0002_entrega_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='nafta',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
