# Generated by Django 4.2 on 2024-09-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrega', '0003_nafta_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='litrosGastados',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
