# Generated by Django 4.2 on 2024-06-05 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entrega', '0002_entrega_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Litro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('precioVenta', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('litro', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='producto.litro')),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productoEntrega', to='entrega.entrega')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productoEntrega', to='producto.producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='tipoProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='producto.tipoproducto'),
        ),
    ]
