# Generated by Django 4.2 on 2024-06-05 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='litro',
            name='cantidad',
            field=models.FloatField(null=True),
        ),
    ]
