# Generated by Django 4.2 on 2024-06-08 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_litro_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
