# Generated by Django 4.2 on 2024-06-08 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_producto_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoproducto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
