# Generated by Django 4.2 on 2024-09-15 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_litro_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='costo',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precioVenta',
            field=models.FloatField(null=True),
        ),
    ]
