# Generated by Django 4.2 on 2024-09-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0006_alter_producto_costo_alter_producto_precioventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fechaCreacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
