# Generated by Django 4.2 on 2024-09-17 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0007_producto_fechacreacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fechaCreacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
