# Generated by Django 4.2 on 2024-09-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0008_alter_producto_fechacreacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoentrega',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
